# Cross.toml

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main-centos"

# may be removed when cross version > 0.2.4
[target.i686-unknown-freebsd]
image = "ghcr.io/cross-rs/i686-unknown-freebsd:main"

# may be removed when cross version > 0.2.4
[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:main"
