name: Build Shared Libraries

on:
  push:
    branches: [main]

jobs:
  buildLibs:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: i686-unknown-linux-gnu

          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - os: macos-12
            target: aarch64-apple-darwin

          - os: macos-12
            target: x86_64-apple-darwin

          - os: windows-2022
            target: i686-pc-windows-msvc

          - os: windows-2022
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    env:
      RURE_VERSION: 1.7.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-20.04'
        uses: docker/setup-qemu-action@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cross
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cross

      - name: Set up regexp repo
        run: |
          git clone -b ${RURE_VERSION} https://github.com/rust-lang/regex.git
        shell: bash

      - name: Build librure shared library
        run: |
          cd regex/regex-capi
          case "$RUNNER_OS" in
            "Linux")
              CARGO=cross
              ;;
            *)
              CARGO=cargo
              rustup target add ${{ matrix.target }}
              ;;
          esac
          ${CARGO} build --release --target ${{ matrix.target }}
        shell: bash
